language: node_js
node_js:
  - "stable"
sudo: false
cache:
  directories:
    - node_modules
script: make test-coveralls
notifications:
  webhooks:
    urls:
      - https://nulab-inc.com/hubot/travis?room=3741
    on_success: change
