language: node_js
node_js:
  - "stable"
sudo: false
cache:
  directories:
    - node_modules
env:
  - HUBOT_VERSION="^3.0"
script:
  - npm install hubot@"$HUBOT_VERSION"
  - npm run lint
after_success:
  - npm run report-coverage
